# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages


notifications:
  email:
    recipients:
    - hadley@rstudio.com
    - winston@rstudio.com
    on_success: change
    on_failure: change

