language: r
warnings_are_errors: true

r_binary_packages:
  - Rcpp
  - cairo
  - knitr

notifications:
  email:
    recipients:
    - hadley@rstudio.com
    - winston@rstudio.com
    on_success: change
    on_failure: change

branches:
  except:
  - /-expt$/
